spring:
  application:
    name: teacher-management
  jackson:
    time-zone: Asia/Seoul
  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:mysql://34.64.114.157:3306/mcompanyDB?verifyServerCertificate=false&useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true
    username: mcompany
    password: Mcompany123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        content_type: text/html
        character_encoding: UTF-8

  sql:
    init:
      mode: never

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
    suffix: .html

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  tomcat:
    max-http-form-post-size: 50MB
    max-swallow-size: 50MB

logging:
  level:
    root: INFO
    com.teacher.management: DEBUG

solapi:
  api-key: NCS8SJGHTGM6FUUC
  api-secret: NJJ75DAUNKVONMKT3MC7MEISD8BF7FUM
  domain: https://api.solapi.com
  from-number: 010-4134-7463
